version: '3.7'

services:

  mysql:
    image: mariadb:10.11
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: GPgpCBQCcDAnWmASrLNmcT6SB
    restart: unless-stopped

  hashtopolis:
    image: kpeiruza/hashtopolis:latest
#    image: htp:latest  # use this if you built your own image using 'docker build <PATH_TO_DOCKERFILE> -t htp:latest'
    depends_on:
      - mysql
    environment:
      H8_USER: lucas  # This is the username you'll be logging into Hashtopolis with
      H8_PASS: Luke1221**  # This is the password you'll be logging into Hashtopolis with
      H8_EMAIL: lucas@lucasserver.cloud
      MYSQL_HOST: srv-captain--mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: GPgpCBQCcDAnWmASrLNmcT6SB
      MYSQL_DB: hashtopolis
      HTP_SERVER_NAME: hashtopolis.lucasserver.cloud
      HTP_MEMORY_LIMIT: 512M
      HTP_UPLOAD_MAX_SIZE: 500M
    volumes:
      - import:/var/www/html/import
      - files:/var/www/html/files
      - inc:/var/www/html/inc
      - locks:/var/www/html/inc/utils/locks
    ports:
      - "8000:80"
    restart: unless-stopped

volumes:
  import: {}
  files: {}
  inc: {}
  locks: {}
  mysql: {}
